@startuml
scale 350 width
[*] --> NotShooting

state NotShooting {
  [*] --> Idle
  Idle --> Configuring
  Configuring --> Idle
}

state Configuring {
  [*] --> NewValueSelection
  NewValueSelection --> NewValuePreview
  NewValuePreview --> NewValueSelection
  NewValuePreview --> NewValueSelection

  state NewValuePreview {
     State1 -> State2
  }

}
@enduml